language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
install: 
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - wget https://dl.bintray.com/jfrog/jfrog-cli-go/1.7.1/jfrog-cli-linux-amd64/jfrog
  - chmod +x jfrog
  - ./jfrog rt config --url "https://cishell.jfrog.io/cishell/" --user $CI_DEPLOY_USERNAME --apikey $CI_DEPLOY_PASSWORD
script: 
  - mvn clean deploy
  - cd update-site/target/repository
  - ./../../../jfrog rt upload "./*(.xml|.jar)" "milestones/updates/" --flat=false --recursive=true